stages:
  - install
  - test

install:
  stage: install
  tags:
    - ciao
  script:
    - echo # Creating artifact
  artifacts:
    expire_in: 2h
    untracked: true
    paths:
      - build-boot
      - build/

test_01:
  stage: test
  tags:
    - ciao
  script:
    - export "PATH=/ciao/build/bin:$PATH"
    - cd /builds/ciao-lang/sCASP/src/
    - ciaoc -o run_test01 test.pl
    - ./run_test01
